---
#inpath : "/rsgrps/gbeslastudents/nicolas/MWLMC_sims/100M/fidutials/MWLMC5_b1/"
inpath : "/home/ngc/Work/research/MW_anisotropy/code/test_snaps/"
snapname : "MWLMC5_100M_new_b1"
#outpath : "/rsgrps/gbeslastudents/nicolas/MWLMC_sims/BFE/MW/MWLMC5/"
outpath : "/home/ngc/Work/research/MW_anisotropy/code/test_snaps/"
outname : "BFE_MWLMC5_b1"
npartHalo : 100000000
samplePart : 700000
nmax : 10
lmax : 5
mmax : 5
rs : 40.85 
ncores : 4
mpi : 1
rhaloCut : 400
initSnap : 110
finalSnap : 111
SatBFE : 1
Satrs : 20
nmaxSat : 20
lmaxSat : 20
mmaxSat : 20
HostBFE : 1
SatBoundParticles : 1
HostSatUnboundPart : 1
WriteSnapsAscii : 0
OutIdsBoundUnbound : 1
PlotScatterSample : 0 
samplePartSat : 50000
snapformat : 1
variance : True
...

