---
inpath : "/home/xzk/work/github/MW_anisotropy/code/test_snaps/"
snapname : "MWLMC3_100M_new_b0"
outpath : "/home/xzk/work/github/bfe-py/outputs/"
outname : "MWLMC3_100M_test"
npartHalo : 100000000
samplePart : 100000
nmax : 10
lmax : 1
rs : 40.85
ncores : 2
mpi : 1
rhaloCut : 400
initSnap : 90
finalSnap : 91
SatBFE : 1
Satrs : 10
nmaxSat : 20
lmaxSat : 8
HostBFE : 0
SatBoundParticles : 1
HostSatUnboundPart : 0
WriteSnapsAscii : 0
OutIdsBoundUnbound : 1
PlotScatterSample : 1
samplePartSat : 20000

...

